Update serialsend

diff --git a/root/usr/bin/serialsend b/root/usr/bin/serialsend
--- a/root/usr/bin/serialsend
+++ b/root/usr/bin/serialsend
@@ -1,20 +1,20 @@
 #!/bin/sh
 
-SERIAL_PORT="/dev/ttyS0" # Assicurati che questo sia il percorso corretto della tua porta seriale
-BAUD_RATE="9600"
+. /usr/bin/webcam.cfg
+
 SIGNAL=$1 # Esempio: un byte ACK. Sostituisci con il tuo segnale desiderato
 
-stty -F "$SERIAL_PORT" "$BAUD_RATE" cs8 -parenb -cstopb 2>/dev/null
+stty -F "$WC_SERIAL_PORT" "$BAUD_RATES" cs8 -parenb -cstopb 2>/dev/null
 
 if [ $? -ne 0 ]; then
-	echo "Errore: Impossibile configurare la porta seriale $SERIAL_PORT" >&2
+	echo "Errore: Impossibile configurare la porta seriale $WC_SERIAL_PORT" >&2
 	exit 1
 fi
 
-printf "$SIGNAL" > "$SERIAL_PORT"
+printf "$SIGNAL" > "$WC_SERIAL_PORT"
 
 # Controlla se l'invio è andato a buon fine (opzionale ma consigliato)
 if [ $? -ne 0 ]; then
-	echo "Errore: Impossibile inviare il segnale sulla porta seriale $SERIAL_PORT" >&2
+	echo "Errore: Impossibile inviare il segnale sulla porta seriale $WC_SERIAL_PORT" >&2
 	exit 1
 fi
